# Generated by Django 6.1.1 on 2026-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='peso',
            field=models.IntegerField(default=250),
        ),
    ]
